name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build_and_push:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build and push the Docker image
      run: |
        docker login -u elle-n-lu --password-stdin safdsfEWAFE3243$@Q__CSE2QE2 ghcr.io
        docker build . --tag ghcr.io/elle-n-lu/md-ghcr:latest
        docker push ghcr.io/elle-n-lu/md-ghcr:latest
