name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build and push:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build and push the Docker image
      run: |
        docker login --username elle-n-lu --password ${{ secrets.CI_K8_REPO_SECRET }} ghcr.io
        docker build . --tag ghcr.io/elle-n-lu/md-ghcr:latest
        docker push ghcr.io/elle-n-lu/md-ghcr:latest
